#!/usr/bin/env ruby
require 'json'
require 'net/http'

ARGV.each do |instance|
  outfolder = "./#{instance.sub(/^https?:\/\//, '').gsub('.', '_')}_emoji" 
  
  instance = 'https://' + instance.sub(/^https?:\/\//, '')
  
  emojiList =
    JSON.parse(
      Net::HTTP.get(
        URI.parse(instance + '/api/v1/custom_emojis')))
  
  Dir.mkdir(outfolder)
  
  Dir.chdir(outfolder) do
    emojiList.each do |e|
      puts "Saving #{e['shortcode']} to #{outfolder}/#{e['shortcode']}.png"
        
      File.write("#{e['shortcode']}.png",
                 Net::HTTP.get(URI.parse(e['url'])))
    end
  end
end
